version: '3.9'

services:
  api:
    build: ./api
    command: ["npm", "run", "start"]
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - NODE_ENV=development
    # ports:
    #   - "5000:5000"
    links: 
      - mongodb
    depends_on:
      - mongodb

  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
    links:
      - api

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db

  proxy:
    image: nginx:1.17
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  node-modules:
  data: