version: '3.9'

services:
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - '80:80'
  api:
    build: ./api
    command: ["npm", "run", "start"]
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    links: 
      - mongodb
    depends_on:
      - mongodb

  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
    links:
      - api

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db


volumes:
  node-modules:
  data: