version: '3.9'

services:
  api:
    build: ./api
    command: ["npm", "run", "start"]
    volumes:
      - ./api:/api
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    links: 
      - mongodb
    depends_on:
      - mongodb

  client:
    build: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/client
      - node-modules:/client/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3030:3030'
    depends_on:
      - api

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes: 
      - data:/data/db


volumes:
  node-modules:
  data: